image: ubuntu:groovy

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq
  - apt-get install -qq texlive-base python3-pip cmake

everything:
  stage: build
  parallel:
    matrix:
      - CC: clang-9
        CXX: clang++-9
        PACKAGE: clang-9
      - CC: clang-10
        CXX: clang++-10
        PACKAGE: clang-10
      - CC: clang-11
        CXX: clang++-11
        PACKAGE: clang-11
      - CC: gcc-9
        CXX: g++-9
        PACKAGE: g++-9
      - CC: gcc-10
        CXX: g++-10
        PACKAGE: g++-10
  script:
    - apt-get install -qq $PACKAGE
    - cmake -B build
    - cmake --build build
