image: ubuntu:focal

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq
  - apt-get install -qq texlive-base python3-pip clang-9 clang-10 cmake
  - pip3 install -q conan

everything:
  stage: build
  parallel:
    matrix:
      - CXX: [clang++-9, clang++-10, g++-9, g++-10]
  script:
    - cmake -B build
    - cmake --build build
