image: ubuntu:focal

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq
  - apt-get install -qq texlive-base python3-pip clang-9 clang-10 gcc-9 gcc-10 cmake
  - pip3 install -q conan

everything:
  stage: build
  parallel:
    matrix:
      - CC: clang-9
        CXX: clang++-9
      - CC: clang-10
        CXX: clang++-10
      - CC: gcc-9
        CXX: g++-9
      - CC: gcc-10
        CXX: g++-10
  script:
    - cmake -B build
    - cmake --build build
