name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:    
      matrix:
        cxx: [g++-9, clang++]
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel 
        python -m pip install conan
        sudo apt-get install doxygen graphviz texlive-base gcc-8 gcc-9

    - name: configure
      env:
        CXX: ${{ matrix.cxx }}      
      run: cmake -B build
      
    - name: make
      run: cmake --build build
